### ISSUE TITLE
Missing installation step

### ISSUE THREAD

**Issue by joewxboy** [playground/hzn-cli#41]
When installing and running on macOS for the first time (with hzn already installed), I got an error about a missing file:

`/Users/yourloginhere/config/.env-support`

After touching the file and re-running `oh deploy -h` it no longer threw an error.

**Comment by playground** [comment]
hmm, @joewxboy  npm i -g hzn-cli should run postinstall to setup those files.  Did you get any any error while installing?

**Comment by playground** [comment]
Added missing .env-support file
