### ISSUE TITLE
Docker run instructions incorrect

### ISSUE THREAD

**Issue by joewxboy** [playground/hzn-cli#73]
In the `README` you have:

> Containerized version is available here `docker pull playbox21/hzn-cli[amd64|arm]`

The container name is missing an underscore between "hzn-cli" and the architecture.  Try changing the docs to something like:

To download the containerized version for your architecture, using one of the following:

For `x86_64` architectures use:

```
docker pull playbox21/hzn-cli_amd64
```

For `armhf` architectures use:

```
docker pull playbox21/hzn-cli_arm64
```

For `armv6` or `arm32` use:

```
docker pull playbox21/hzn-cli_arm
```

**Comment by playground** [comment]
Updated readme with reference to auto-dock, and removed mentioning of hzn-cli docker image.
